name: Playwright QA Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Playwright install karo
        run: |
          pip install playwright pytest-playwright
          playwright install chromium  # browser download hoga

      - name: Tests chalao
        run: pytest CICD-TestCases/TestCases/FirstTest.py --screenshot=on

      - name: Screenshots aur report save karo
        uses: actions/upload-artifact@v6
        if: always()
        with:
          name: playwright-results
          path: |
            screenshots/
            test-results/
